# Generated by Django 4.0.4 on 2022-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='Book Description', null=True)),
                ('in_library', models.BooleanField(default=True)),
            ],
        ),
    ]
