# Generated by Django 3.2.2 on 2021-05-08 07:28

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('acc_no', models.CharField(max_length=12)),
                ('class_no', models.CharField(max_length=12)),
                ('isbn', models.CharField(max_length=32)),
                ('date', models.DateField(auto_now=True)),
                ('borrowed', models.BooleanField(default=False)),
                ('days_left', models.IntegerField(default=14)),
                ('subject', models.CharField(max_length=22)),
                ('publisher', models.CharField(max_length=32)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('house', models.CharField(choices=[('CHA', 'CHAMPAGNAT'), ('CHI', 'CHICHESTER'), ('MIC', 'MICHEAL'), ('PAT', 'PATRICK')], max_length=3)),
                ('ref_code', models.CharField(max_length=8)),
                ('has_returned', models.BooleanField(default=False)),
                ('borrowed_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.book')),
            ],
        ),
    ]
