# Generated by Django 3.2.2 on 2021-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210512_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='borrowed_book',
        ),
    ]
