# Generated by Django 3.1.6 on 2021-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_borrowed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
