# Generated by Django 3.2.2 on 2022-04-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210520_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='acc_no',
        ),
        migrations.RemoveField(
            model_name='book',
            name='borrowed_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='class_no',
        ),
        migrations.RemoveField(
            model_name='book',
            name='days_left',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_returned',
        ),
        migrations.RemoveField(
            model_name='student',
            name='house',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ref_code',
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.student'),
        ),
    ]
