# Generated by Django 3.2.2 on 2022-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220402_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='tk', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_books',
            field=models.IntegerField(default=0),
        ),
    ]
